<div class="t_g_box t_news_newest">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator('supplier_category').': '.$this->category->name; ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>
    </div>
    <div class="t_g_box_content">
    	<div>
		<?php if ($this->suppliers != null) : ?>
			<ul>
			<?php foreach ($this->suppliers as $index => $supplier) : ?>
			<li>
				<a href="<?php echo $this->url($supplier->getProperties(), 'supplier_index_view'); ?>"><strong><?php echo $supplier->name; ?></strong></a>
			</li>
			<?php endforeach; ?>
			</ul>
		<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
		<?php endif; ?>
		</div>
	</div>	
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>