<?php 
$this->headTitle($this->translator('supplier_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span><span><a href="<?php echo $this->url(array(), 'supplier_index_list'); ?>"><?php echo $this->translator('supplier_list_breadcump'); ?></a></span><span><?php echo $this->translator('supplier_edit_breadcump'); ?></span>	
</div>

<div class="grid_12">
<?php echo $this->flashMessenger(); ?>
</div>

<form method="post" action="<?php echo $this->url(array('supplier_id' => $this->supplier->supplier_id), 'supplier_index_edit'); ?>" id="editSupplierForm" class="t_a_form">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('supplier_add_guide'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_name'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="name" name="name" value="<?php if ($this->supplier != null) : ?><?php echo $this->supplier->name; ?><?php endif; ?>" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_slug'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="slug" name="slug" value="<?php if ($this->supplier != null) : ?><?php echo $this->supplier->slug; ?><?php endif; ?>" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_address'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="address" name="address" value="<?php if ($this->supplier != null) : ?><?php echo $this->supplier->address; ?><?php endif; ?>" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_phone'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="phone" name="phone" value="<?php if ($this->supplier != null) : ?><?php echo $this->supplier->phone; ?><?php endif; ?>" style="width: 400px" maxlength="50" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_email'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="email" name="email" value="<?php if ($this->supplier != null) : ?><?php echo $this->supplier->email; ?><?php endif; ?>" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_hour_open'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="hour_open" name="hour_open" value="<?php if ($this->supplier != null) : ?><?php echo $this->supplier->hour_open; ?><?php endif; ?>" style="width: 400px" maxlength="5" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_hour_close'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="hour_close" name="hour_close" value="<?php if ($this->supplier != null) : ?><?php echo $this->supplier->hour_close; ?><?php endif; ?>" style="width: 400px" maxlength="5" /></div>
	</div>
	
	
	<div class="grid_10 prefix_2 alpha"><input type="submit" class="t_a_button" value="<?php echo $this->translator('supplier_add_save_button'); ?>" /></div>
</div>
</form>
<script type="text/javascript">
$(document).ready(function() {
	$.validator.addMethod('slug', function(value) {
		var regex = new RegExp(/^[a-z0-9\-]+$/);
		if (value.match(regex)) {
			return true;
		} else {
			return false;
		}
	}); 
	$('#editSupplierForm').validate({
		rules: {
			name: {
				required: true,
		  		maxlength: 255
			},
			slug: {
		  		required: true,
		  		slug: true,
		  		maxlength: 255
			}
	    },
	    messages: {
	    	name: {
	        	required: "<?php echo $this->translator('supplier_name_required'); ?>",
				maxlength: "<?php echo $this->translator('supplier_name_maxlength'); ?>"
			},
			slug: { 
	        	required: "<?php echo $this->translator('supplier_slug_required'); ?>",
	        	slug: "<?php echo $this->translator('supplier_slug_validate'); ?>",
	        	maxlength: "<?php echo $this->translator('supplier_slug_maxlength'); ?>"
	    	}
		}
	});
});
</script>
