<?php 
$this->headTitle($this->translator('supplier_list_page_title'));
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.draggable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.resizable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><?php echo $this->translator('supplier_list_breadcump'); ?></span>	
</div>
<div class="grid_12">
<?php echo $this->flashMessenger(); ?>
</div>
<div class="grid_12 t_a_bottom">
	<div class="prefix_9 grid_3 alpha t_a_textright">
		<a href="<?php echo $this->url(array(), 'supplier_index_add'); ?>" class="t_a_link"><?php echo $this->translator('supplier_add_breadcump'); ?></a>
	</div>
</div>

<div class="grid_12 t_a_bottom">
	<div class="grid_6 alpha t_a_line">
		<div></div>
		<h2><?php echo $this->translator('supplier_name'); ?></h2>
	</div>
	<div class="grid_2 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('supplier_status'); ?></h2>
	</div>
	<div class="grid_1 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('supplier_id'); ?></h2>
	</div>
	<div class="grid_3 omega t_a_line">
		<div></div>
		<h2><?php echo $this->translator('supplier_list_action'); ?></h2>
	</div>
</div>
<?php if ($this->numSuppliers == 0) : ?>
	<div class="grid_12 t_a_bottom"><?php echo $this->translator('supplier_list_not_found'); ?></div>	
<?php else : ?>
	<?php foreach ($this->suppliers as $supplier) :?>
	<div id="tsupplierRow_<?php echo $supplier->supplier_id; ?>" class="grid_12">
		<div class="clearfix t_a_box">
			<div>
				<div class="grid_6 alpha">
					<div style="padding-left: 5px">
						<?php echo $supplier->name; ?>
					</div>
				</div>
				<div class="grid_2" id="tsupplierStatus_<?php echo $supplier->supplier_id; ?>">
				<?php if ($supplier->is_active == 1) : ?>
					<?php echo $this->translator('supplier_list_status_activated'); ?>
				<?php else : ?>
					<?php echo $this->translator('supplier_list_status_not_activated'); ?>
				<?php endif; ?>
				</div>
				<div class="grid_1"><?php echo $supplier->supplier_id; ?></div>
				<div class="grid_3 omega">
					<?php if ($this->allow('edit')) : ?>
					<a class="t_a_link" href="<?php echo $this->url(array('supplier_id' => $supplier->supplier_id), 'supplier_index_edit'); ?>"><?php echo $this->translator('supplier_list_action_edit'); ?></a> |
					<?php endif; ?>
					<?php if ($this->allow('delete')) : ?> 
					<a class="t_a_link tDeleteAction" rel="<?php echo $supplier->supplier_id; ?>" href="javascript: void(0)"><?php echo $this->translator('supplier_list_action_delete'); ?></a> |
					<?php endif; ?>
					<?php if ($this->allow('activate')) : ?>
					<a class="t_a_link tActivateAction" rel="<?php echo $supplier->supplier_id; ?>_<?php echo $supplier->is_active; ?>" href="javascript: void(0)"><?php if ($supplier->is_active == 1) : ?><?php echo $this->translator('supplier_list_action_deactivate'); ?><?php else : ?><?php echo $this->translator('supplier_list_action_activate'); ?><?php endif; ?></a><?php endif; ?>
				</div>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
	<div class="grid_12 t_a_bottom t_a_paginator">
		<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
	</div>
<?php endif; ?>

<div id="tDialogContainer"></div>

<script type="text/javascript">
$(document).ready(function() {
	<?php if ($this->allow('delete')) : ?>
	$('a.tDeleteAction').click(function() {
		if (confirm('<?php echo $this->escape($this->translator('supplier_list_action_delete_confirm')); ?>')) {
			$(this).html('').addClass('t_a_loading');
			var id = $(this).attr('rel');
			$.ajaxq('news_article', {
				type: 'POST',
				url: '<?php echo $this->url(array(), 'supplier_index_delete'); ?>',
				data: { id: id },
				success: function(response) {
					response = $.evalJSON(response);
					$('#tsupplierRow_' + id).fadeOut('slow');
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('supplier_list_delete_supplier_success')); ?>', response.title))
					.dialog({
						title: '<?php echo addslashes($this->translator('supplier_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				}
			});
		}
	});
	<?php endif; ?>
	<?php if ($this->allow('activate')) : ?>
	$('a.tActivateAction').click(function() {
		var self = this;
		var arr = $(this).attr('rel').split('_');
		$(self).html('').addClass('t_a_loading');
		$.ajaxq('supplier_activate', {
			url: '<?php echo $this->url(array(), 'supplier_index_activate'); ?>',
			type: 'POST',
			data: { id: arr[0], status: arr[1] },
			success: function(response) {
				response = $.evalJSON(response);
				//$(self).attr('rel', arr[0] + '_' + response);
				
				if (response.is_active == 1) {
					$('#tsupplierStatus_' + arr[0]).html("<?php echo $this->translator('supplier_list_status_activated'); ?>");
					$(self).html("<?php echo $this->translator('supplier_list_action_deactivate'); ?>");
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('supplier_list_active_supplier_success')); ?>', response.name))
					.dialog({
						title: '<?php echo addslashes($this->translator('supplier_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				} else {
					$('#tsupplierStatus_' + arr[0]).html("<?php echo $this->translator('supplier_list_status_not_activated'); ?>");
					$(self).html("<?php echo $this->translator('supplier_list_action_activate'); ?>");
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('supplier_list_inactive_supplier_success')); ?>', response.name))
					.dialog({
						title: '<?php echo addslashes($this->translator('supplier_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				}
				$(self).removeClass('t_a_loading');
			}
		});
	});
	<?php endif; ?>
});
</script>