<h1>List of contacts</h1>
 
<style type="text/css">
.dataTable{
  border: 1px solid;
}
.dataTable td{
  border: 1px solid;
  padding: 5px;
}
.dataTable th{
  border: 1px solid;
  padding: 5px;
  background: #000;
  color: #fff;
}
</style>
 
<table class="dataTable">
  <thead>
    <tr>
      <th><?php echo $this->translator('contact_list_ID'); ?></th>
      <th><?php echo $this->translator('contact_list_first_name'); ?></th>
      <th><?php echo $this->translator('contact_list_last_name'); ?></th>
      <th><?php echo $this->translator('contact_list_tel'); ?></th>
      <th><?php echo $this->translator('contact_list_address'); ?></th>
      <th><?php echo $this->translator('contact_list_email'); ?></th>
    </tr>
  </thead>
  <tbody >
    <?php foreach($this->contacts as $contact):?>
    <tr >
      <td><?php echo $contact->contact_id; ?></td>
      <td><?php echo $contact->first_name; ?></td>
      <td><?php echo $contact->last_name; ?></td>
      <td><?php echo $contact->tel; ?></td>
      <td><?php echo $contact->address; ?></td>
      <td><?php echo $contact->email; ?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<div>
   <?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
</div>