<div id="t_a_header_welcome">
	<?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
		<?php echo $this->translator('menu_welcome', 'core');?>	
		<a class="t_a_link" href="<?php echo $this->url(array(), 'core_user_update'); ?>">
			<?php echo Zend_Auth::getInstance()->getIdentity()->user_name; ?></a> 
		| <a class="t_a_link" href="<?php echo $this->url(array(), 'core_auth_logout'); ?>">
			<?php echo $this->translator('menu_logout', 'core'); ?></a>
	<?php else: ?>
		<a class="t_a_link" href="<?php echo $this->url(array(), 'core_user_register'); ?>">
			<?php echo $this->translator('menu_register', 'core'); ?></a>
		| <a class="t_a_link" href="<?php echo $this->url(array(), 'core_auth_user_login'); ?>">
			<?php echo $this->translator('menu_login', 'core'); ?></a>
	<?php endif; ?>
</div>	
<div class="grid_4 alpha">
	<a href="<?php echo $this->baseUrl(); ?>"><img src="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/images/logo.png" width="175px" height="53px" alt="<?php echo $this->SITE_NAME; ?>" /></a>
</div>
