<?php 
$this->headTitle($this->translator('supplier_view_page_title'));
?>
<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>
<div class="grid_12">
<div class="grid_4">
<?php
	if(!empty($this->supplier->image_general)){
		echo '<img border="0" src="'.$this->supplier->image_general.'" width="200">';
	}
?>
</div>
<div class="grid_7">
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_name'); ?>:</label></div>
		<div class="grid_5 omega"><?php if ($this->supplier != null) : ?><?php echo $this->supplier->name; ?><?php endif; ?></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_slug'); ?>:</label></div>
		<div class="grid_5 omega"><?php if ($this->supplier != null) : ?><?php echo $this->supplier->slug; ?><?php endif; ?></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_address'); ?>:</label></div>
		<div class="grid_5 omega"><?php if ($this->supplier != null) : ?><?php echo $this->supplier->address; ?><?php endif; ?></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_phone'); ?>:</label></div>
		<div class="grid_5 omega"><?php if ($this->supplier != null) : ?><?php echo $this->supplier->phone; ?><?php endif; ?></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_email'); ?>:</label></div>
		<div class="grid_5 omega"><?php if ($this->supplier != null) : ?><?php echo $this->supplier->email; ?><?php endif; ?></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_hour_open'); ?>:</label></div>
		<div class="grid_5 omega"><?php if ($this->supplier != null) : ?><?php echo $this->supplier->hour_open; ?><?php endif; ?></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('supplier_hour_close'); ?>:</label></div>
		<div class="grid_5 omega"><?php if ($this->supplier != null) : ?><?php echo $this->supplier->hour_close; ?><?php endif; ?></div>
	</div>
	</div>
</div>
