<div class="t_g_box t_news_newest">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('newest_suppliers'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>
    </div>
    <div class="t_g_box_content">
    	<div>
		<?php if ($this->suppliers != null) : ?>
			<ul>
			<?php foreach ($this->suppliers as $index => $supplier) : ?>
			<li>
				<strong><a href="<?php echo $this->url($supplier->getProperties(), 'supplier_index_cate'); ?>"><?php echo $supplier->name; ?></a></strong>
			</li>
			<?php endforeach; ?>
			</ul>
		<?php endif; ?>
		</div>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>

