<?php 
$this->headTitle($this->translator('user_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
?>
<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>
<div class="grid_12 t_a_bottom"><?php echo $this->translator('user_edit_guide'); ?></div>
<form method="post" action="<?php echo $this->url(array(), 'core_user_update'); ?>" id="editUserForm" class="t_a_form">
<div class="grid_12 t_a_bottom">
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_full_name'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" style="width: 400px" name="fullname" id="fullname" value="<?php if (null != $this->user && null != $this->user->full_name) : ?><?php echo $this->user->full_name; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_password'); ?>:</label></div>
		<div class="grid_10 omega"><input type="password" style="width: 400px" name="password" id="password" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_confirm_password'); ?>:</label></div>
		<div class="grid_10 omega"><input type="password" style="width: 400px" name="confirmPassword" id="confirmPassword" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_email'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" style="width: 400px" name="email" id="email"  value="<?php if (null != $this->user && null != $this->user->email) : ?><?php echo $this->user->email; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="prefix_2 grid_6 alpha">
			<input type="button" class="t_a_button" value="<?php echo $this->translator('user_edit_save_button'); ?>" onclick="javascript: $('#editUserForm').submit();" />
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	$('#editUserForm').validate({
		rules: {
			fullname: {
				required: true
			},
			email: {
				required: true,
				email: true,
				remote: '<?php echo $this->url(array('check_type' => 'email'), 'core_user_check'); ?>?original=<?php echo $this->user->email; ?>'
			},
			password: {
		  		minlength: 5
			},
			confirmPassword: {
				equalTo: '#password'
			}
	    },
	    messages: {
	    	fullname: {
	        	required: "<?php echo $this->translator('user_full_name_required'); ?>"
	    	},
			email: { 
				required: "<?php echo $this->translator('user_email_required'); ?>",
	        	email: "<?php echo $this->translator('user_email_invalid'); ?>",
		        remote: "<?php echo $this->translator('user_email_exist'); ?>"
	    	},
	    	password: {
	    		minlength: "<?php echo $this->translator('user_password_minlength'); ?>"
			},
			confirmPassword: {
				equalTo: "<?php echo $this->translator('user_confirm_password_error'); ?>"
			}
		}
	});
});
</script>
